#!/bin/bash
# 
# RUN NCC =======================================================================================
#
shopt -s globstar
rm -f REPORT_COMPLEXITY_CONDITIONAL;
cd Paintings91/Images/
cp ../../paq8kx_v7.exe .
#
# ===============================================================================================
declare -a NAMES=( "ALBRECHT_DURER" "AMEDEO_MODIGLIANI" "ANDREA_MANTEGNA" "ANDY_WARHOL" "ARSHILLE_GORKY" "CAMILLE_COROT" "CARAVAGGIO" "CASPAR_DAVID_FRIEDRICH" "CLAUDE_LORRAIN" "CLAUDE_MONET" "DANTE_GABRIEL_ROSSETTI" "DAVID_HOCKNEY" "DIEGO_VELAZQUEZ" "EDGAR_DEGAS" "EDVARD_MUNCH" "EDWARD_HOPPER" "EGON_SCHIELE" "EL_LISSITZKY" "EUGENE_DELACROIX" "FERNAND_LEGER" "FRANCISCO_DE_GOYA" "FRANCISCO_DE_ZURBARAN" "FRANCIS_BACON" "FRANS_HALS" "FRANZ_MARC" "FRA_ANGELICO" "FRIDA_KAHLO" "Frederic_Edwin_Church" "GENTILESCHI_ARTEMISIA" "GEORGES_BRAQUE" "GEORGES_DE_LA_TOUR" "GEORGES_SEURAT" "GEORGIA_OKEEFE" "GERHARD_RICHTER" "GIORGIONE" "GIORGIO_DE_CHIRICO" "GIOTTO_DI_BONDONE" "GUSTAVE_COURBET" "GUSTAVE_MOREAU" "GUSTAV_KLIMT" "HANS_HOLBEIN_THE_YOUNGER" "HANS_MEMLING" "HENRI_MATISSE" "HIERONYMUS_BOSCH" "JACKSON_POLLOCK" "JACQUES-LOUIS_DAVID" "JAMES_ENSOR" "JAMES_MCNEILL_WHISTLER" "JAN_VAN_EYCK" "JAN_VERMEER" "JASPER_JOHNS" "JEAN-ANTOINE_WATTEAU" "JEAN-AUGUSTE-DOMINIQUE_INGRES" "JEAN-MICHEL_BASQUIAT" "JEAN_FRANCOIS_MILLET" "JOACHIM_PATINIR" "JOAN_MIRO" "JOHN_CONSTABLE" "JOSEPH_MALLORD_WILLIAM_TURNER" "KAZIMIR_MALEVICH" "LUCIO_FONTANA" "MARC_CHAGALL" "MARK_ROTHKO" "MAX_ERNST" "NICOLAS_POUSSIN" "PAUL_CEZANNE" "PAUL_GAUGUIN" "PAUL_KLEE" "PETER_PAUL_RUBENS" "PIERRE-AUGUSTE_RENOIR" "PIETER_BRUEGEL_THE_ELDER" "PIET_MONDRIAN" "Picasso" "RAPHAEL" "REMBRANDT_VAN_RIJN" "RENE_MAGRITTE" "ROGER_VAN_DER_WEYDEN" "ROY_LICHTENSTEIN" "SALVADOR_DALI" "SANDRO_BOTTICELLI" "THEODORE_GERICAULT" "TINTORETTO" "TITIAN" "UMBERTO_BOCCIONI" "VINCENT_VAN_GOGH" "WASSILY_KANDINSKY" "WILLEM_DE_KOONING" "WILLIAM_BLAKE" "WILLIAM_HOGARTH" "WINSLOW_HOMER" "РDOUARD_MANET" )
  #
  #
  rm -f NC_AVERAGE_TMP;
  for i in "${NAMES[@]}"
  do
    #
    SUM_SIZE=0;
    declare -a AUTH_NAME;
    readarray AUTH_NAME < <(ls -d *.jpg.pgm | grep $i)
    #
    rm -f NCC_LOOP_NAMES;
    for j in "${AUTH_NAME[@]}"
      do
      printf "Compressing $j";
      rm -fr ncc_archive
      ./paq8kx_v7.exe -8 ncc_archive $j;
      COMPRESSED_SIZE=`ls -la ncc_archive.paq8kx | awk '{ print $5;}'`;
      SUM_SIZE=$((SUM_SIZE+COMPRESSED_SIZE));
      echo "$j" | tr '\n' ' ' >> NCC_LOOP_NAMES;
      done
    #
    rm -f ncc_archive2.paq8kx;
    names_to_compress=`cat NCC_LOOP_NAMES`;
    ./paq8kx_v7.exe -8 ncc_archive2 $names_to_compress;
    COMPRESSED_CONDITIONAL_SIZE=`ls -la ncc_archive2.paq8kx | awk '{ print $5;}'`;
    printf "\"$i\"" >> ../../REPORT_COMPLEXITY_CONDITIONAL;
    echo "scale=8; ($COMPRESSED_CONDITIONAL_SIZE/$SUM_SIZE)" \
    | bc -l | awk '{printf "\t%f\n", $0}' >> ../../REPORT_COMPLEXITY_CONDITIONAL;
    #
  done
# ===============================================================================================
